### ISSUE TITLE
Want to add backtracking solutions

### ISSUE THREAD

**Issue by glacias07** [BeeBombshell/Python-DSA#116]
I have written the code for knights tour and n-queens and will add more soon. Can I make the pull request?

**Comment by BeeBombshell** [comment]
Sure, @glacias07. You can add a PR and tag me (@BeeBombshell) or @BhavyaT-135 for a quick review.

**Comment by BhavyaT-135** [comment]
I guess the code for this issue has already been added @BeeBombshell. I'm closing this issue 👍
